default:
  context:
    parameters:
      base_url: "http://composer.symfony.local/app_test.php"
  formatter:
    name: progress
  extensions:
    Behat\Symfony2Extension\Extension:
      mink_driver: true
      kernel:
        env: test
        debug: true
    Behat\MinkExtension\Extension:
      base_url: 'http://composer.symfony.local/app_test.php'
      default_session: symfony2
